### ISSUE TITLE
error  'Undefined index: REDIRECT_URL'

### ISSUE THREAD

**Issue by Imohamed** [alve89/PHPMobileConfig#1]
i got erro msg

`Fatal error: Uncaught exception 'ErrorException' with message 'Undefined index: REDIRECT_URL' in C:\wamp64\www\apple\classes\class.helper.php on line 319
( ! ) ErrorException: Undefined index: REDIRECT_URL in C:\wamp64\www\apple\classes\class.helper.php on line 319`

**Comment by alve89** [comment]
You got this error message because $_SERVER['REDIRECT_URL'] isn't set. Why isn't it set? If you tell me, I'll fix for future releases.
Until this you can fix this quick and dirty by commenting out [line 33 in /inc.ssl.php](https://github.com/alve89/PHPMobileConfig/blob/master/inc.ssl.php#L33) and set `$url` to your path:
`$url = "http://myDomain.tld/path/to/software/";`

Does this work for you?

**Comment by shineabraham** [comment]
i got this error on running index.php. can you tell me how I could run this program for custom SSID and password
Fatal error: Uncaught ErrorException: Undefined index: QUERY_STRING in /Users/shineabraham/Documents/AGREEFY/Research and Development/mobileconfig-iOS/PHPMobileConfig/classes/class.helper.php:312
Stack trace:
#0 /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/classes/class.helper.php(312): {closure}(8, 'Undefined index...', '/Users/shineabr...', 312, Array)
#1 /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/inc.ssl.php(33): HELPER::setURL('https://')
#2 /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/index.php(12): require_once('/Users/shineabr...')
#3 {main}
  thrown in /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/classes/class.helper.php on line 312
