### ISSUE TITLE
Undefined index: QUERY_STRING

### ISSUE THREAD

**Issue by shineabraham** [alve89/PHPMobileConfig#2]
i got this error on running index.php. can you tell me how I could run this program for custom SSID and password
Fatal error: Uncaught ErrorException: Undefined index: QUERY_STRING in /Users/shineabraham/Documents/AGREEFY/Research and Development/mobileconfig-iOS/PHPMobileConfig/classes/class.helper.php:312
Stack trace:
#0 /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/classes/class.helper.php(312): {closure}(8, 'Undefined index...', '/Users/shineabr...', 312, Array)
#1 /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/inc.ssl.php(33): HELPER::setURL('https://')
#2 /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/index.php(12): require_once('/Users/shineabr...')
#3 {main}
thrown in /Users/shineabraham/Documents/mobileconfig-iOS/PHPMobileConfig/classes/class.helper.php on line 312

**Comment by alve89** [comment]
It's like the same question you asked in issue #1 - unfortunately I can't tell you why your PHP server does not set these variables. You can fix this by
1. Running phpinfo()
2. Get the server variable `$_SERVER['XXXXXX']`, where `XXXXXX` is the name of the variable that stores the query (it's the bold part of e. g. https://domain.tld/?**key1=value1&key2=value2**)
3. Change line https://github.com/alve89/PHPMobileConfig/blob/1f916564a2078fac31818ca375057fc84e2ca1f9/classes/class.helper.php#L312 from `$query = explode('&', $_SERVER['QUERY_STRING']);` to `$query = explode('&', $_SERVER['XXXXXX']);`


If you tell me your variable-name afterwards, I can implement this additionally for the next version of the library.
